name: publish
on:
  push:
    tags:
      - v*


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        include:
          - project: agoric
            version: agoric-3.1
          - project: akash
            version: v0.16.3
          - project: bandchain
            version: v2.3.3
          - project: comdex
            version: v0.1.1
          - project: cosmoshub
            version: v7.0.2
          - project: evmos
            version: v8.2.0
          - project: gravitybridge
            version: v1.4.1
          - project: juno
            version: v10.0.2
          - project: kava
            version: v0.16.1
          - project: lumnetwork
            version: v1.0.5
          - project: osmosis
            version: v12.0.0
          - project: passage
            version: v1.0.0
          - project: persistence
            version: v0.1.3
          - project: sentinel
            version: v0.8.3
          - project: shentu
            version: v2.5.0
          - project: sifchain
            version: v1.0-beta.12-issuefix
          - project: starname
            version: v0.10.18
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build
        run: |
          touch .env # Create dummy env file
          cd ${{matrix.project}}
          docker buildx bake -f build.yml --set node_1.tags=ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/}-${{matrix.project}}-${{matrix.version}}${{matrix.tag_suffix}} --push
  build_generic:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 15
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build
        run: |
          touch .env # Create dummy env file
          cd generic
          docker buildx bake -f build.yml --set node_1.tags=ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/}-generic --push
